"""
RAJAN Export System
Export findings in multiple formats for use in other tools
JSON, CSV, TXT, HackerOne-ready, Bugcrowd-ready
"""

import json
import os
import datetime


class Exporter:
    def __init__(self, memory, session_id):
        self.memory = memory
        self.session_id = session_id
        os.makedirs("reports", exist_ok=True)

    def _base_filename(self):
        session = self.memory.get_session(self.session_id)
        target = session.get("target", "target") if session else "target"
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"reports/export_{target}_{ts}"

    def export_json(self):
        """Export all findings + intel as JSON"""
        findings = self.memory.get_findings(self.session_id)
        intel = self.memory.get_intel(self.session_id)
        session = self.memory.get_session(self.session_id)
        counts = self.memory.count_findings(self.session_id)

        intel_formatted = []
        for row in intel:
            if len(row) == 5:
                _, itype, key, value, ts = row
            else:
                itype, key, value = row
                ts = ""
            intel_formatted.append({"type": itype, "key": key, "value": value, "timestamp": ts})

        data = {
            "rajan_export": True,
            "version": "1.0.0",
            "exported_at": datetime.datetime.now().isoformat(),
            "session": {
                "id": self.session_id,
                "target": session.get("target") if session else "",
                "scope": session.get("scope") if session else "",
                "started": session.get("started_at") if session else "",
            },
            "summary": counts,
            "total_findings": len(findings),
            "findings": findings,
            "intel": intel_formatted,
        }

        filename = f"{self._base_filename()}.json"
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, default=str)
        return filename

    def export_csv(self):
        """Export findings as CSV for spreadsheet analysis"""
        findings = self.memory.get_findings(self.session_id)
        filename = f"{self._base_filename()}.csv"

        with open(filename, "w", encoding="utf-8") as f:
            f.write("ID,Title,Severity,Location,Description,Proof,MITRE,Found At\n")
            for i, finding in enumerate(findings, 1):
                def esc(s):
                    return f'"{str(s).replace(chr(34), chr(39))}"'
                f.write(
                    f"{i},{esc(finding['title'])},{esc(finding['severity'])},"
                    f"{esc(finding.get('location',''))},"
                    f"{esc(finding['description'])},"
                    f"{esc(finding.get('proof',''))},"
                    f"{esc(finding.get('mitre_technique',''))},"
                    f"{esc(finding.get('found_at',''))}\n"
                )
        return filename

    def export_txt(self):
        """Plain text summary — paste anywhere"""
        findings = self.memory.get_findings(self.session_id)
        session = self.memory.get_session(self.session_id)
        counts = self.memory.count_findings(self.session_id)
        filename = f"{self._base_filename()}.txt"
        date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"RAJAN Penetration Test Results\n")
            f.write(f"{'='*50}\n")
            f.write(f"Target  : {session.get('target','') if session else ''}\n")
            f.write(f"Date    : {date}\n")
            f.write(f"Session : {self.session_id}\n")
            f.write(f"Critical: {counts.get('CRITICAL',0)}\n")
            f.write(f"High    : {counts.get('HIGH',0)}\n")
            f.write(f"Medium  : {counts.get('MEDIUM',0)}\n")
            f.write(f"Low     : {counts.get('LOW',0)}\n")
            f.write(f"Total   : {len(findings)}\n\n")
            f.write(f"FINDINGS\n{'='*50}\n\n")

            for i, finding in enumerate(findings, 1):
                f.write(f"[{i}] {finding['title']}\n")
                f.write(f"    Severity : {finding['severity']}\n")
                f.write(f"    Location : {finding.get('location','N/A')}\n")
                f.write(f"    MITRE    : {finding.get('mitre_technique','N/A')}\n")
                f.write(f"    Desc     : {finding['description']}\n")
                if finding.get('proof'):
                    f.write(f"    Proof    : {finding['proof']}\n")
                f.write("\n")

            f.write(f"\nGenerated by RAJAN v1.0.0\n")
            f.write(f"github.com/DHRUVIL-5/RAJAN\n")

        return filename

    def export_hackerone(self):
        """Format findings as HackerOne-ready report templates"""
        findings = self.memory.get_findings(self.session_id)
        session = self.memory.get_session(self.session_id)
        filename = f"{self._base_filename()}_hackerone.md"

        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"# HackerOne Submission Templates\n")
            f.write(f"Generated by RAJAN | Target: {session.get('target','') if session else ''}\n\n")
            f.write(f"---\n\n")

            high_value = [x for x in findings if x['severity'] in ('CRITICAL','HIGH')]
            for i, finding in enumerate(high_value, 1):
                f.write(f"## Report #{i}: {finding['title']}\n\n")
                f.write(f"**Severity:** {finding['severity']}\n\n")
                f.write(f"### Summary\n")
                f.write(f"{finding['description']}\n\n")
                f.write(f"### Steps to Reproduce\n")
                f.write(f"1. Navigate to: `{finding.get('location','[URL]')}`\n")
                f.write(f"2. [Add detailed steps here]\n")
                f.write(f"3. Observe the vulnerability\n\n")
                f.write(f"### Impact\n")
                f.write(f"[Describe business impact — what can attacker do?]\n\n")
                f.write(f"### Supporting Material\n")
                if finding.get('proof'):
                    f.write(f"```\n{finding['proof']}\n```\n\n")
                f.write(f"---\n\n")

        return filename

    def export_all(self):
        """Export all formats at once"""
        results = {}
        results['json'] = self.export_json()
        results['csv'] = self.export_csv()
        results['txt'] = self.export_txt()
        results['hackerone'] = self.export_hackerone()
        return results
