"""RAJAN Reporter Agent — Auto-generates professional pentest reports"""
import datetime
import os
from agents.base import BaseAgent


class ReporterAgent(BaseAgent):
    def __init__(self, memory, llm, logger, session_id, target):
        super().__init__(memory, llm, logger, session_id, target)
        self.name = "ReporterAgent"

    def run_task(self, task_name):
        return self.generate_report()

    def generate_report(self):
        self.logger.info("Generating final pentest report", "Reporter")
        findings = self.memory.get_findings(self.session_id)
        intel = self.memory.get_intel(self.session_id)
        counts = self.memory.count_findings(self.session_id)
        session = self.memory.get_session(self.session_id)
        date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

        severity_emoji = {
            "CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"
        }

        # Executive summary via LLM
        finding_titles = [f["title"] for f in findings]
        exec_summary = self.ask_llm(
            f"Write a 3-sentence executive summary for a penetration test on {self.target}. "
            f"Findings: {finding_titles}. Be professional and concise."
        ) if findings else "No vulnerabilities were confirmed during this assessment."

        report = f"""# 🔐 RAJAN Penetration Test Report

## Executive Summary
**Target:** {self.target}
**Date:** {date}
**Session ID:** {self.session_id}
**Scope:** {session.get('scope', 'Full target') if session else 'N/A'}

{exec_summary}

## Risk Summary
| Severity | Count |
|----------|-------|
| 🔴 Critical | {counts.get('CRITICAL', 0)} |
| 🟠 High | {counts.get('HIGH', 0)} |
| 🟡 Medium | {counts.get('MEDIUM', 0)} |
| 🟢 Low | {counts.get('LOW', 0)} |
| **Total** | **{len(findings)}** |

## Intelligence Gathered
"""
        intel_by_type = {}
        for _, itype, key, value, _ in intel:
            intel_by_type.setdefault(itype, []).append(f"{key}: {value}")
        for itype, items in intel_by_type.items():
            report += f"\n### {itype.upper()}\n"
            for item in items[:10]:
                report += f"- {item}\n"

        report += "\n## Findings\n"
        if not findings:
            report += "_No confirmed vulnerabilities found._\n"
        else:
            for i, f in enumerate(findings, 1):
                emoji = severity_emoji.get(f["severity"].upper(), "⚪")
                report += f"""
### {i}. {f['title']} {emoji}
**Severity:** {f['severity']}
**Location:** {f.get('location', 'N/A')}
**MITRE ATT&CK:** {f.get('mitre_technique', 'N/A')}

**Description:** {f['description']}

**Proof:** {f.get('proof', 'N/A')}

**Remediation:** _(See OWASP guidelines for {f['title']})_

---
"""

        report += f"""
## Methodology
This assessment followed a structured approach:
1. Passive Reconnaissance (DNS, WHOIS, OSINT)
2. Active Scanning (Port, Service, Web fingerprinting)
3. Vulnerability Testing (Web, Auth, API, Cloud)
4. Exploit Validation (PoC confirmation, no exploitation)
5. Reporting

## Disclaimer
> This report was generated by **RAJAN** for authorized security testing only.
> All testing was performed within the defined scope.
> Generated: {date}

---
*RAJAN — AI Ethical Hacking Agent | github.com/DHRUVIL-5/RAJAN*
"""
        # Save report
        os.makedirs("reports", exist_ok=True)
        filename = f"reports/report_{self.target}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        with open(filename, "w", encoding="utf-8") as f_out:
            f_out.write(report)

        self.logger.success(f"Report saved: {filename}", "Reporter")
        return filename
